#!/usr/bin/python3
import pandas as pd
import glob, argparse, re 


def selectFiles(mydir, listID):
    """ choose files if ID in list id is in the filename""" 
    fileList=[]
    for ind in listID: 
        fileList += [f for f in glob.glob(mydir) if re.search(ind, f) ]
    return fileList

def mergeThat(fileList):
    df = pd.DataFrame()
    for f in fileList:
        tmp = pd.read_csv(f,sep="\t", index_col='index_x')
        #tmp = tmp[["csqAllele", "impact","element_id", "type", "csqCount", "gene_id", "gene_symbol","most_severe_consequence", "start", "id", "rare", "commonCSQall", "EmbryoDev", "DDD", "Lethal", "Essential", "Misc", "soScore", "pLI", "chr", "CADD"]]
        df = df.append(tmp)
    return df


def main(): 
    parser = argparse.ArgumentParser()
    parser.add_argument("-f", help="path to  input dir  ",type=str,required=True)
    parser.add_argument("-l", help="list of id ",type=str,required=True)
    parser.add_argument("-n", help="number of individual to sample ",type=int,required=True)
    parser.add_argument("-i", help="number of iterations ",type=int,required=True) 
    args = parser.parse_args()

    listID = [line.rstrip('\n') for line in open(args.l)]
    sampleToConsider=random.sample(listID, args.n)
    print (sampleToConsider)
    #listID=['HGDP00518', 'HGDP01152']
    fileToConsider=selectFiles(args.f, listID)
    myd=mergeThat(fileToConsider)
    myd.to_csv("cicci", sep="\t", index=True)

if __name__ == "__main__": 
    main() 
